MotChallenge2DBox
MPNTrack
Traceback (most recent call last):
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\eval.py", line 180, in evaluate
    metric.plot_single_tracker_results(table_res, tracker_display_name, c_cls,
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\metrics\hota.py", line 185, in plot_single_tracker_results
    from matplotlib import pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'





MotChallenge2DBox
DEEPSORTTrack
Traceback (most recent call last):
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\eval.py", line 222, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\datasets\mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\datasets\_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-09, frame: 1, ids: -1)





MotChallenge2DBox
DEEPSORTTrack
Traceback (most recent call last):
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\eval.py", line 222, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\datasets\mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\datasets\_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-09, frame: 1, ids: -1)





MotChallenge2DBox
DEEPSORTTrack
Traceback (most recent call last):
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\eval.py", line 222, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\datasets\mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "C:\Users\maria\dev\HSE\deepDT\hota\trackeval\datasets\_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-09, frame: 1, ids: -1)





